List dataItems = [
  {
    "id": 2,
    "code": "Mr Gereon Kapuire",
    "name": "+264 61 207 2334",
    "img":
        "http://fci.nust.na/sites/default/files/pictures/xpicture-50-1453724322.jpg.pagespeed.ic.ayNgv7vibS.webp",
    "price": "Information Technology House",
    "promotionPrice": 15.00,
    "email": "gkapuire@nust.na",
    "Occup": "Deputy HOD: Software Engineering, Lecturer",
  },
  {
    "id": 3,
    "code": "Ms Loini Iiyambo",
    "name": "+264 61 207 2446",
    "img":
        "http://fci.nust.na/sites/default/files/pictures/xpicture-76-1453724789.jpg.pagespeed.ic.iD2HP8jtpe.webp",
    "price": "Information Technology House",
    "promotionPrice": 12.5,
    "email": "liiyambo@nust.na",
    "Occup":
        "Deputy HOD: System Administration & Computer Networking, Lecturer ",
  },
  {
    "id": 4,
    "code": "Mr Simon Muchinenyika",
    "name": "+264 61 207 2054",
    "img":
        "http://fci.nust.na/sites/default/files/pictures/xpicture-85-1463649922.jpg.pagespeed.ic.9ZSLbF4TXG.webp",
    "price": "Poly Height, Room 404",
    "promotionPrice": 11.00,
    "email": "smuchinenyika@nust.na",
    "Occup": "Lecturer",
  },
  {
    "id": 5,
    "code": "Mr Julius Silaa",
    "name": "+264 61 207 2037",
    "img":
        "http://fci.nust.na/sites/default/files/pictures/xpicture-148-1532084538.jpg.pagespeed.ic.Lm5TpoOTxJ.webp",
    "price": "Poly Heights 401",
    "promotionPrice": 13.00,
    "email": " ",
    "Occup": "Lecturer",
  },
  {
    "id": 6,
    "code": "Ms Ndinelago Nashandi",
    "name": "+264 61 207 2911",
    "img":
        "http://fci.nust.na/sites/default/files/pictures/picture-52-1453724847.jpg",
    "price": "Information Technology House",
    "promotionPrice": 17.00,
    "email": "nnashandi@nust.na",
    "Occup": "Lecturer",
  },
  {
    "id": 7,
    "code": "Mr Herman Kandjimi",
    "name": "+264 61 207 2782",
    "img":
        "http://fci.nust.na/sites/default/files/pictures/picture-63-1453724874.jpg",
    "price": "Information Technology House",
    "promotionPrice": 11.50,
    "email": "hkandjimi@nust.na",
    "Occup": "Lecturer",
  },
  {
    "id": 8,
    "code": "Ms Albertina Shilongo",
    "name": "+264 61 207 2691",
    "img":
        "http://fci.nust.na/sites/default/files/pictures/xpicture-121-1487598165.jpg.pagespeed.ic.rmInnLqgc5.webp",
    "price": "",
    "promotionPrice": 11.50,
    "email": "ashilongo@nust.na",
    "Occup": "Junior Lecturer",
  },
  {
    "id": 9,
    "code": "Ms Teresia Ankome",
    "name": "+264 61 207 2420",
    "img":
        "http://fci.nust.na/sites/default/files/pictures/xpicture-122-1523465481.jpg.pagespeed.ic.vzgz0Fy4dL.webp",
    "price": " IT House",
    "promotionPrice": 11.50,
    "email": "tankome@nust.na",
    "Occup": "Junior Lecturer",
  },
  {
    "id": 10,
    "code": "Mr Edward Nepolo",
    "name": "+264 61 207 2520",
    "img":
        "http://fci.nust.na/sites/default/files/pictures/picture-134-1521399065.jpg",
    "price": "Poly Heights",
    "promotionPrice": 11.50,
    "email": "enepolo@nust.na",
    "Occup": "Junior Lecturer",
  },
  {
    "id": 11,
    "code": "Ms Uakomba Mbasuva",
    "name": "+264 61 207 2761",
    "img":
        "http://fci.nust.na/sites/default/files/pictures/picture-150-1534146571.jpg",
    "price": "SIT House",
    "promotionPrice": 11.50,
    "email": "umbasuva@nust.na",
    "Occup": "Junior Lecturer",
  },
  {
    "id": 12,
    "code": "Ms Jovita N Mateus",
    "name": "+264 61 207 9111",
    "img":
        "http://fci.nust.na/sites/default/files/pictures/picture-151-1534241568.jpg",
    "price": "SIT House",
    "promotionPrice": 11.50,
    "email": "",
    "Occup": "Junior Lecturer",
  },
  {
    "id": 13,
    "code": "Prof. Heike Winschiers",
    "name": "+264 61 207 2169",
    "img":
        "http://fci.nust.na/sites/default/files/pictures/xpicture-37-1438097439.jpg.pagespeed.ic.f6UddliWHc.webp",
    "price": "heikew@nust.na",
    "promotionPrice": 13.00,
    "email": " ",
    "Occup": "Professor",
  },
  {
    "id": 14,
    "code": "Prof. Dharm Singh Jat",
    "name": "+264 61 207 2991",
    "img":
        "http://fci.nust.na/sites/default/files/pictures/xpicture-35-1453724226.jpg.pagespeed.ic.30jy7Notfj.webp",
    "price": "Information Technology House",
    "promotionPrice": 13.00,
    "email": "dsingh@nust.na",
    "Occup": "Professor",
  },
  {
    "id": 15,
    "code": "Prof. Guy-Alain Lusilao Zodi",
    "name": "+264 61 207 2774",
    "img":
        "http://fci.nust.na/sites/default/files/pictures/xpicture-66-1453724388.jpg.pagespeed.ic.cIjnj5k5_P.webp",
    "price": "FCI Building 017",
    "promotionPrice": 11.50,
    "email": "gzodi@nust.na",
    "Occup": "HOD, Associate Professor ",
  },
  {
    "id": 16,
    "code": "Prof. Jürgen Sieck",
    "name": "+264 815 531 371",
    "img":
        "http://fci.nust.na/sites/default/files/pictures/picture-120-1458121941.jpg",
    "price": "",
    "promotionPrice": 13.00,
    "email": "j.sieck@htw-berlin.de",
    "Occup": "Professor",
  },
  {
    "id": 17,
    "code": "Prof. Jose Quenum",
    "name": "+264 61 207 2235",
    "img":
        "http://fci.nust.na/sites/default/files/pictures/xpicture-33-1453723781.jpg.pagespeed.ic.3sbbLvPlzV.webp",
    "price": "",
    "promotionPrice": 13.00,
    "email": "jquenum@nust.na",
    "Occup": "Associate Professor",
  },
  {
    "id": 18,
    "code": "Prof Fungai Shava",
    "name": "+264 61 207 2510",
    "img":
        "http://fci.nust.na/sites/default/files/pictures/xpicture-27-1463649798.jpg.pagespeed.ic.SO2QXmNPr3.webp",
    "price": "IT House",
    "promotionPrice": 13.00,
    "email": "fbshava@nust.na",
    "Occup": "Associate Dean: Research and Innovation",
  },
  {
    "id": 19,
    "code": "Mr Isaac Nhamu",
    "name": "+264 61 207 2975",
    "img":
        "http://fci.nust.na/sites/default/files/pictures/picture-84-1453724452.jpg",
    "price": "Information Technology House",
    "promotionPrice": 13.00,
    "email": "inhamu@nust.na",
    "Occup": "Lecturer",
  },
  {
    "id": 20,
    "code": "Mr Isaac Nhamu",
    "name": "+264 61 207 2975",
    "img":
        "http://fci.nust.na/sites/default/files/pictures/picture-84-1453724452.jpg",
    "price": "Information Technology House",
    "promotionPrice": 13.00,
    "email": "inhamu@nust.na",
    "Occup": "Lecturer",
  },
  {
    "id": 21,
    "code": "Mrs Shilumbe Chivuno",
    "name": "+264 61 207 2057",
    "img":
        "http://fci.nust.na/sites/default/files/pictures/xpicture-57-1463649892.jpg.pagespeed.ic.mjXJtQJh9f.webp",
    "price": "Information Technology House",
    "promotionPrice": 13.00,
    "email": "mbere@nust.na",
    "Occup": "Lecturer",
  },
  {
    "id": 22,
    "code": "Mrs Mercy Chitauro",
    "name": "+264 61 207 2039",
    "img":
        "http://fci.nust.na/sites/default/files/pictures/picture-41-1438155196.jpg",
    "price": "Information Technology House",
    "promotionPrice": 13.00,
    "email": "schivuno@nust.na",
    "Occup": "Lecturer",
  },
  {
    "id": 23,
    "code": "Mr. Steven U Tjiraso",
    "name": "+264 61 207 2097",
    "img":
        "http://fci.nust.na/sites/default/files/pictures/xpicture-153-1549959991.jpg.pagespeed.ic.-d4rdTwhWA.webp",
    "price": "Information Technology House",
    "promotionPrice": 13.00,
    "email": "",
    "Occup": "Junior Lecturer",
  },
  {
    "id": 24,
    "code": "Ms Rachel Amundaba",
    "name": "+264 61 207 2052",
    "img":
        "http://fci.nust.na/sites/default/files/pictures/xpicture-38-1463648218.jpg.pagespeed.ic.Xw6qSmPaVy.webp",
    "price": "Information Technology House",
    "promotionPrice": 13.00,
    "email": "ramundaba@nust.na",
    "Occup": "Secretary",
  },
  {
    "id": 25,
    "code": "Mr Shoopala Nambahu",
    "name": "+264 61 207 2550",
    "img":
        "http://fci.nust.na/sites/default/files/pictures/picture-135-1521561198.png",
    "price": "Poly Heights 401",
    "promotionPrice": 13.00,
    "email": "nshoopala@nust.na",
    "Occup": "Junior Lecturer",
  },
  {
    "id": 26,
    "code": "Ms Rosetha Kays",
    "name": "+264 61 207 2405",
    "img":
        "http://fci.nust.na/sites/default/files/pictures/xpicture-78-1453724927.jpg.pagespeed.ic.Rqp_k-YS9Z.webp",
    "price": "Information Technology House",
    "promotionPrice": 13.00,
    "email": "rkays@nust.na",
    "Occup": "Lecturer",
  },
  {
    "id": 27,
    "code": "Ms Josephina Mikka",
    "name": "+264 61 207 2741",
    "img":
        "http://fci.nust.na/sites/default/files/pictures/picture-71-1463649959.jpg",
    "price": "Information Technology House",
    "promotionPrice": 13.00,
    "email": "jmikka@nust.na",
    "Occup": "Lecturer",
  },
  {
    "id": 28,
    "code": "Mr Shadreck Chitauro",
    "name": "+264 61 207 2689",
    "img":
        "http://fci.nust.na/sites/default/files/pictures/xpicture-56-1453724673.jpg.pagespeed.ic.R3euHuacJn.webp",
    "price": "",
    "promotionPrice": 13.00,
    "email": "schitauro@nust.na",
    "Occup": "Junior Lecturer",
  },
  {
    "id": 29,
    "code": "Mr Nasimane Ekandjo",
    "name": "+264 61 207 2572",
    "img":
        "http://fci.nust.na/sites/default/files/pictures/xpicture-47-1453724813.jpg.pagespeed.ic.Ilx6uzHsK_.webp",
    "price": "Information Technology House",
    "promotionPrice": 13.00,
    "email": " nekandjo@nust.na",
    "Occup": "Junior Lecturer",
  },
  {
    "id": 30,
    "code": "Dr Attlee M Gamundani",
    "name": "+264 61 207 2525",
    "img":
        "http://fci.nust.na/sites/default/files/pictures/picture-86-1463649941.jpg",
    "price": "2nd floor, PolyHeights",
    "promotionPrice": 13.00,
    "email": "agamundani@nust.na",
    "Occup": "Senior Lecturer",
  },
];
